// src/components/general/HeroSection.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { assetUrl } from "../../lib/assets.js";

type SlideLogo = {
  source: string;
  alt: string;
  href: string;
  newTab: boolean;
  width: string;
  positionX: string;
  positionY: string;
  opacity: number;
};

type Slide = {
  id: number;
  title: string;
  subtitle: string;
  video: string;
  thumbnail: string | null;
  logo: SlideLogo | null;
};

type PauseReason = "visibility";

const CROSSFADE_DURATION = 1_800;
const SERVER_URL = "https://modrinth.com/server/brassworks-smp-official-server";

const slides: Slide[] = Array.from({ length: 5 }, (_, index) => ({
  id: index + 1,
  title: "Create: Brassworks",
  subtitle: "Season 2",
  video: assetUrl("/videos/background.mp4"),
  thumbnail: null,
  logo: {
    source: assetUrl("/images/seasons/season2.png"),
    alt: "Brassworks Season 2",
    href: SERVER_URL,
    newTab: true,
    width: "min(560px, 70vw)",
    positionX: "50%",
    positionY: "45%",
    opacity: 1,
  },
}));

function waitUntilReady(video: HTMLVideoElement): Promise<void> {
  if (video.readyState >= HTMLMediaElement.HAVE_CURRENT_DATA) {
    return Promise.resolve();
  }

  return new Promise((resolve) => {
    const finish = () => {
      video.removeEventListener("canplay", finish);
      video.removeEventListener("error", finish);
      video.removeEventListener("abort", finish);
      resolve();
    };

    video.addEventListener("canplay", finish, { once: true });
    video.addEventListener("error", finish, { once: true });
    video.addEventListener("abort", finish, { once: true });
  });
}

export function HeroSection() {
  const [activeIndex, setActiveIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const activeIndexRef = useRef(0);
  const videoElements = useRef<Array<HTMLVideoElement | null>>([]);
  const pauseReasons = useRef(new Set<PauseReason>());
  const transitionTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const switchToken = useRef(0);
  const pendingIndex = useRef(0);
  const mounted = useRef(false);

  const activeSlide = slides[activeIndex];

  const pauseAllVideos = useCallback(() => {
    videoElements.current.forEach((video) => video?.pause());
  }, []);

  const startVideo = useCallback(async (index: number) => {
    const video = videoElements.current[index];

    if (!video) return;

    await waitUntilReady(video);

    if (!mounted.current) return;

    video.currentTime = 0;

    if (pauseReasons.current.size > 0 || document.hidden) return;

    try {
      await video.play();
    } catch {}
  }, []);

  const resumeActiveVideo = useCallback(async () => {
    if (pauseReasons.current.size > 0 || document.hidden) return;

    const video = videoElements.current[activeIndexRef.current];

    if (!video) return;

    await waitUntilReady(video);

    if (!mounted.current || pauseReasons.current.size > 0) {
      return;
    }

    try {
      await video.play();
    } catch {}
  }, []);

  const pauseCarousel = useCallback(
    (reason: PauseReason) => {
      pauseReasons.current.add(reason);
      pauseAllVideos();
    },
    [pauseAllVideos],
  );

  const resumeCarousel = useCallback(
    (reason: PauseReason) => {
      pauseReasons.current.delete(reason);

      if (pauseReasons.current.size === 0) {
        void resumeActiveVideo();
      }
    },
    [resumeActiveVideo],
  );

  const selectSlide = useCallback(
    async (index: number) => {
      const normalizedIndex = (index + slides.length) % slides.length;
      const token = ++switchToken.current;

      pendingIndex.current = normalizedIndex;
      setProgress(0);

      await startVideo(normalizedIndex);

      if (!mounted.current) return;

      if (token !== switchToken.current) {
        if (pendingIndex.current !== normalizedIndex) {
          videoElements.current[normalizedIndex]?.pause();
        }

        return;
      }

      activeIndexRef.current = normalizedIndex;
      setActiveIndex(normalizedIndex);

      if (transitionTimer.current) {
        clearTimeout(transitionTimer.current);
      }

      transitionTimer.current = setTimeout(() => {
        videoElements.current.forEach((video, videoIndex) => {
          if (videoIndex !== activeIndexRef.current) {
            video?.pause();
          }
        });
      }, CROSSFADE_DURATION);
    },
    [startVideo],
  );

  useEffect(() => {
    mounted.current = true;
    pendingIndex.current = activeIndexRef.current;

    videoElements.current.forEach((video, index) => {
      if (index !== activeIndexRef.current) {
        video?.pause();
      }
    });

    if (document.hidden) {
      pauseCarousel("visibility");
    } else {
      void startVideo(activeIndexRef.current);
    }

    let frameId = 0;

    const tick = () => {
      const activeVideo = videoElements.current[activeIndexRef.current];

      if (
        activeVideo &&
        Number.isFinite(activeVideo.duration) &&
        activeVideo.duration > 0
      ) {
        setProgress(
          Math.min((activeVideo.currentTime / activeVideo.duration) * 100, 100),
        );
      }

      frameId = window.requestAnimationFrame(tick);
    };

    const handleVisibilityChange = () => {
      if (document.hidden) {
        pauseCarousel("visibility");

        if (transitionTimer.current) {
          clearTimeout(transitionTimer.current);
        }

        return;
      }

      resumeCarousel("visibility");
    };

    const handlePageHide = () => {
      pauseCarousel("visibility");

      if (transitionTimer.current) {
        clearTimeout(transitionTimer.current);
      }
    };

    const handlePageShow = () => {
      if (!document.hidden) {
        resumeCarousel("visibility");
      }
    };

    frameId = window.requestAnimationFrame(tick);
    document.addEventListener("visibilitychange", handleVisibilityChange);
    window.addEventListener("pagehide", handlePageHide);
    window.addEventListener("pageshow", handlePageShow);

    return () => {
      mounted.current = false;
      window.cancelAnimationFrame(frameId);

      if (transitionTimer.current) {
        clearTimeout(transitionTimer.current);
      }

      pauseAllVideos();
      document.removeEventListener("visibilitychange", handleVisibilityChange);
      window.removeEventListener("pagehide", handlePageHide);
      window.removeEventListener("pageshow", handlePageShow);
    };
  }, [pauseAllVideos, pauseCarousel, resumeCarousel, startVideo]);

  return (
    <section
      id="create"
      className="relative h-[72svh] min-h-[500px] max-h-[620px] overflow-hidden bg-[#171614] text-white md:h-auto md:min-h-svh md:max-h-none"
      aria-roledescription="carousel"
      aria-label="Featured Brassworks creations"
    >
      <div className="absolute inset-x-3 bottom-3 top-[70px] md:inset-[60px]">
        <div className="outer absolute inset-0 overflow-hidden !rounded-[18px] md:!rounded-[24px]">
          {slides.map((slide, index) => {
            const isActive = activeIndex === index;

            return (
              <video
                key={slide.id}
                ref={(element) => {
                  videoElements.current[index] = element;
                }}
                className={`absolute inset-0 h-full w-full object-cover opacity-0 transition-opacity duration-[1800ms] ease-[cubic-bezier(0.22,1,0.36,1)] will-change-[opacity] ${
                  isActive
                    ? "z-[1] opacity-100"
                    : "pointer-events-none z-0 opacity-0"
                }`}
                muted
                playsInline
                preload="auto"
                aria-hidden={!isActive}
                aria-label={
                  isActive ? `${slide.title}, ${slide.subtitle}` : undefined
                }
                onEnded={() => {
                  if (
                    index === activeIndexRef.current &&
                    pauseReasons.current.size === 0 &&
                    !document.hidden
                  ) {
                    void selectSlide(index + 1);
                  }
                }}
              >
                <source src={slide.video} type="video/mp4" />
              </video>
            );
          })}

          {activeSlide.logo ? (
            <div className="pointer-events-none absolute inset-0 z-[3]">
              <a
                key={activeSlide.id}
                href={activeSlide.logo.href}
                target={activeSlide.logo.newTab ? "_blank" : "_self"}
                rel={
                  activeSlide.logo.newTab ? "noopener noreferrer" : undefined
                }
                className="pointer-events-auto absolute -translate-x-1/2 -translate-y-1/2 transition-transform duration-300 ease-out hover:scale-105"
                style={{
                  width: activeSlide.logo.width,
                  left: activeSlide.logo.positionX,
                  top: activeSlide.logo.positionY,
                  opacity: activeSlide.logo.opacity,
                }}
              >
                <img
                  src={activeSlide.logo.source}
                  alt={activeSlide.logo.alt}
                  className="h-auto w-full select-none object-contain [image-rendering:pixelated]"
                  draggable="false"
                />
              </a>
            </div>
          ) : null}

          <div className="relative z-10 mx-auto flex h-full w-full max-w-[1600px] flex-col justify-end px-3 pb-3 pt-16 md:w-[calc(100%_-_3rem)] md:px-0 md:pb-[40px] md:pt-[82px] lg:w-[calc(100%_-_6rem)]">
            <div
              className="pointer-events-none absolute bottom-0 left-1/2 hidden h-[160px] w-[calc(100%_+_10rem)] max-w-[1760px] -translate-x-1/2 bg-[radial-gradient(ellipse_at_center,rgba(10,9,8,0.7)_0%,rgba(10,9,8,0.42)_38%,rgba(10,9,8,0.16)_58%,transparent_78%)] blur-xl md:block"
              aria-hidden="true"
            />
            <div className="relative z-10 hidden w-full justify-start overflow-x-auto overscroll-x-contain py-3 [scrollbar-color:#7d693f_transparent] md:flex lg:py-4 2xl:justify-center">
              <div
                className="ml-0 grid w-[1100px] min-w-[1100px] grid-cols-5 gap-3 2xl:mx-auto 2xl:w-full 2xl:min-w-0 2xl:max-w-[1450px] 2xl:gap-4"
                role="tablist"
                aria-label="Select a creation"
              >
                {slides.map((slide, index) => {
                  const isActive = activeIndex === index;

                  return (
                    <button
                      key={slide.id}
                      type="button"
                      role="tab"
                      aria-selected={isActive}
                      aria-label={`Show ${slide.title}, item ${index + 1} of ${slides.length}`}
                      className={`relative grid h-[62px] min-w-0 grid-cols-[52px_minmax(0,1fr)] items-center gap-2 overflow-hidden rounded-md border-[1.5px] bg-transparent p-1.5 text-left transition-colors md:h-[68px] md:grid-cols-[65px_minmax(0,1fr)] md:gap-3 ${
                        isActive
                          ? "border-[#d9b86e]"
                          : "border-white/30 hover:border-white/70"
                      }`}
                      onClick={() => void selectSlide(index)}
                    >
                      <span
                        className="pointer-events-none absolute inset-0 z-0"
                        aria-hidden="true"
                      >
                        <span
                          className="block h-full bg-[#c7a35a]/50 transition-[width] duration-75 ease-linear"
                          style={{
                            width: isActive ? `${progress}%` : "0%",
                          }}
                        />
                      </span>

                      <span className="relative z-10 block h-[48px] w-[52px] overflow-hidden rounded-md md:h-[54px] md:w-[65px] md:rounded-lg">
                        {slide.thumbnail ? (
                          <img
                            src={slide.thumbnail}
                            alt={`${slide.title} preview`}
                            className="h-full w-full object-cover"
                            draggable="false"
                          />
                        ) : (
                          <video
                            className="h-full w-full object-cover"
                            muted
                            playsInline
                            preload="metadata"
                            aria-hidden="true"
                          >
                            <source src={slide.video} type="video/mp4" />
                          </video>
                        )}
                      </span>

                      <span className="relative z-10 min-w-0">
                        <strong className="font-minecraft block truncate text-sm">
                          {slide.title}
                        </strong>
                        <small className="mt-1 block truncate text-[10px] font-bold uppercase tracking-[0.12em] text-[#d9b86e]">
                          {slide.subtitle}
                        </small>
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        <a
          href={SERVER_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="group/button absolute bottom-2 right-2 z-30 inline-flex h-11 w-[160px] items-center justify-center overflow-hidden rounded-lg bg-[#c7a35a] px-4 text-[11px] font-bold uppercase tracking-[0.08em] text-[#171614] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#dec17c] md:bottom-[5px] md:right-[5px] md:h-[52px] md:w-auto md:min-w-[230px] md:px-7 md:text-sm"
        >
          <span className="absolute inset-y-0 -left-1/3 w-[140%] -translate-x-full -skew-x-[24deg] bg-[#dec17c] transition-transform duration-500 ease-[cubic-bezier(0.22,1,0.36,1)] group-hover/button:translate-x-0" />
          <span className="relative z-10">See more</span>
        </a>
      </div>
    </section>
  );
}

// src/components/general/HeroSection.vue
<script setup lang="ts">
import {
  computed,
  onBeforeUnmount,
  onMounted,
  ref,
  type ComponentPublicInstance,
} from "vue";
import { assetUrl } from "../../lib/assets";

type SlideLogo = {
  source: string;
  alt: string;
  href: string;
  newTab: boolean;
  width: string;
  positionX: string;
  positionY: string;
  opacity: number;
  linkClass: string;
  imageClass: string;
};

type Slide = {
  id: number;
  title: string;
  subtitle: string;
  video: string;
  thumbnail: string | null;
  logo: SlideLogo | null;
};

type PauseReason = "visibility" | "hover" | "focus";

const CROSSFADE_DURATION = 1_800;

const slides: Slide[] = [
  {
    id: 1,
    title: "Create: Brassworks",
    subtitle: "Season 2",
    video: assetUrl("/videos/background.mp4"),
    thumbnail: null,
    logo: {
      source: assetUrl("/images/seasons/season2.png"),
      alt: "Brassworks Season 2",
      href: "https://modrinth.com/server/brassworks-smp-official-server",
      newTab: true,
      width: "min(560px, 70vw)",
      positionX: "50%",
      positionY: "45%",
      opacity: 1,
      linkClass: "hover:scale-105",
      imageClass: "[image-rendering:pixelated]",
    },
  },
  {
    id: 2,
    title: "Create: Brassworks",
    subtitle: "Season 2",
    video: assetUrl("/videos/background.mp4"),
    thumbnail: null,
    logo: {
      source: assetUrl("/images/seasons/season2.png"),
      alt: "Brassworks Season 2",
      href: "https://modrinth.com/server/brassworks-smp-official-server",
      newTab: true,
      width: "min(560px, 70vw)",
      positionX: "50%",
      positionY: "45%",
      opacity: 1,
      linkClass: "hover:scale-105",
      imageClass: "[image-rendering:pixelated]",
    },
  },
  {
    id: 3,
    title: "Create: Brassworks",
    subtitle: "Season 2",
    video: assetUrl("/videos/background.mp4"),
    thumbnail: null,
    logo: {
      source: assetUrl("/images/seasons/season2.png"),
      alt: "Brassworks Season 2",
      href: "https://modrinth.com/server/brassworks-smp-official-server",
      newTab: true,
      width: "min(560px, 70vw)",
      positionX: "50%",
      positionY: "45%",
      opacity: 1,
      linkClass: "hover:scale-105",
      imageClass: "[image-rendering:pixelated]",
    },
  },
  {
    id: 4,
    title: "Create: Brassworks",
    subtitle: "Season 2",
    video: assetUrl("/videos/background.mp4"),
    thumbnail: null,
    logo: {
      source: assetUrl("/images/seasons/season2.png"),
      alt: "Brassworks Season 2",
      href: "https://modrinth.com/server/brassworks-smp-official-server",
      newTab: true,
      width: "min(560px, 70vw)",
      positionX: "50%",
      positionY: "45%",
      opacity: 1,
      linkClass: "hover:scale-105",
      imageClass: "[image-rendering:pixelated]",
    },
  },
  {
    id: 5,
    title: "Create: Brassworks",
    subtitle: "Season 2",
    video: assetUrl("/videos/background.mp4"),
    thumbnail: null,
    logo: {
      source: assetUrl("/images/seasons/season2.png"),
      alt: "Brassworks Season 2",
      href: "https://modrinth.com/server/brassworks-smp-official-server",
      newTab: true,
      width: "min(560px, 70vw)",
      positionX: "50%",
      positionY: "45%",
      opacity: 1,
      linkClass: "hover:scale-105",
      imageClass: "[image-rendering:pixelated]",
    },
  },
];

const activeIndex = ref(0);
const progress = ref(0);
const videoElements = ref<HTMLVideoElement[]>([]);

const pauseReasons = new Set<PauseReason>();

let frameId = 0;
let transitionTimer: number | undefined;
let switchToken = 0;
let pendingIndex = 0;

const activeSlide = computed(() => slides[activeIndex.value]);

function setVideoRef(
    element: Element | ComponentPublicInstance | null,
    index: number,
): void {
  if (element instanceof HTMLVideoElement) {
    videoElements.value[index] = element;
  }
}

function waitUntilReady(video: HTMLVideoElement): Promise<void> {
  if (video.readyState >= HTMLMediaElement.HAVE_CURRENT_DATA) {
    return Promise.resolve();
  }

  return new Promise((resolve) => {
    const finish = (): void => {
      video.removeEventListener("canplay", finish);
      video.removeEventListener("error", finish);
      video.removeEventListener("abort", finish);
      resolve();
    };

    video.addEventListener("canplay", finish, { once: true });
    video.addEventListener("error", finish, { once: true });
    video.addEventListener("abort", finish, { once: true });
  });
}

function pauseAllVideos(): void {
  videoElements.value.forEach((video) => {
    video.pause();
  });
}

async function resumeActiveVideo(): Promise<void> {
  if (pauseReasons.size > 0 || document.hidden) return;

  const video = videoElements.value[activeIndex.value];

  if (!video) return;

  await waitUntilReady(video);

  if (pauseReasons.size > 0 || document.hidden) return;

  try {
    await video.play();
  } catch {
    return;
  }
}

function pauseCarousel(reason: PauseReason): void {
  pauseReasons.add(reason);
  pauseAllVideos();
}

function resumeCarousel(reason: PauseReason): void {
  pauseReasons.delete(reason);

  if (pauseReasons.size === 0) {
    void resumeActiveVideo();
  }
}

async function startVideo(index: number): Promise<void> {
  const video = videoElements.value[index];

  if (!video) return;

  await waitUntilReady(video);

  video.currentTime = 0;

  if (pauseReasons.size > 0 || document.hidden) return;

  try {
    await video.play();
  } catch {
    return;
  }
}

async function selectSlide(index: number): Promise<void> {
  const normalizedIndex =
      (index + slides.length) % slides.length;

  const token = ++switchToken;

  pendingIndex = normalizedIndex;
  progress.value = 0;

  await startVideo(normalizedIndex);

  if (token !== switchToken) {
    if (pendingIndex !== normalizedIndex) {
      videoElements.value[normalizedIndex]?.pause();
    }

    return;
  }

  activeIndex.value = normalizedIndex;

  window.clearTimeout(transitionTimer);

  transitionTimer = window.setTimeout(() => {
    videoElements.value.forEach((video, videoIndex) => {
      if (videoIndex !== activeIndex.value) {
        video.pause();
      }
    });
  }, CROSSFADE_DURATION);
}

function nextSlide(): void {
  void selectSlide(activeIndex.value + 1);
}

function handleVideoEnded(index: number): void {
  if (
      index !== activeIndex.value ||
      pauseReasons.size > 0 ||
      document.hidden
  ) {
    return;
  }

  nextSlide();
}

function tick(): void {
  const activeVideo = videoElements.value[activeIndex.value];

  if (
      activeVideo &&
      Number.isFinite(activeVideo.duration) &&
      activeVideo.duration > 0
  ) {
    progress.value = Math.min(
        (activeVideo.currentTime / activeVideo.duration) * 100,
        100,
    );
  }

  frameId = window.requestAnimationFrame(tick);
}

function handleVisibilityChange(): void {
  if (document.hidden) {
    pauseCarousel("visibility");
    window.clearTimeout(transitionTimer);
    return;
  }

  resumeCarousel("visibility");
}

function handlePageHide(): void {
  pauseCarousel("visibility");
  window.clearTimeout(transitionTimer);
}

function handlePageShow(): void {
  if (!document.hidden) {
    resumeCarousel("visibility");
  }
}

function handleFocusOut(event: FocusEvent): void {
  const currentTarget = event.currentTarget;
  const nextTarget = event.relatedTarget;

  if (
      currentTarget instanceof HTMLElement &&
      nextTarget instanceof Node &&
      currentTarget.contains(nextTarget)
  ) {
    return;
  }

  resumeCarousel("focus");
}

onMounted(() => {
  pendingIndex = activeIndex.value;

  videoElements.value.forEach((video, index) => {
    if (index !== activeIndex.value) {
      video.pause();
    }
  });

  if (document.hidden) {
    pauseCarousel("visibility");
  } else {
    void startVideo(activeIndex.value);
  }

  frameId = window.requestAnimationFrame(tick);

  document.addEventListener(
      "visibilitychange",
      handleVisibilityChange,
  );

  window.addEventListener("pagehide", handlePageHide);
  window.addEventListener("pageshow", handlePageShow);
});

onBeforeUnmount(() => {
  window.cancelAnimationFrame(frameId);
  window.clearTimeout(transitionTimer);
  pauseAllVideos();

  document.removeEventListener(
      "visibilitychange",
      handleVisibilityChange,
  );

  window.removeEventListener("pagehide", handlePageHide);
  window.removeEventListener("pageshow", handlePageShow);
});
</script>

<template>
  <section
      id="create"
      class="relative min-h-svh overflow-hidden bg-[#171614] text-white"
      aria-roledescription="carousel"
      aria-label="Featured Brassworks creations"
      @focusin="pauseCarousel('focus')"
      @focusout="handleFocusOut"
  >
    <div class="absolute inset-[60px]">
      <div class="outer absolute inset-0">
        <video
            v-for="(slide, index) in slides"
            :key="slide.id"
            :ref="(element) => setVideoRef(element, index)"
            class="absolute inset-0 h-full w-full object-cover opacity-0 transition-opacity duration-[1800ms] ease-[cubic-bezier(0.22,1,0.36,1)] will-change-[opacity]"
            :class="
            activeIndex === index
              ? 'z-[1] opacity-100'
              : 'pointer-events-none z-0 opacity-0'
          "
            muted
            playsinline
            preload="auto"
            :aria-hidden="activeIndex !== index"
            :aria-label="
            activeIndex === index
              ? `${slide.title}, ${slide.subtitle}`
              : undefined
          "
            @ended="handleVideoEnded(index)"
        >
          <source :src="slide.video" type="video/mp4" />
        </video>

        <div
            class="pointer-events-none absolute inset-0 z-[2] bg-[linear-gradient(180deg,rgba(10,9,8,0.28)_0%,rgba(10,9,8,0.02)_42%,rgba(10,9,8,0.92)_100%)]"
            aria-hidden="true"
        ></div>

        <div
            v-if="activeSlide.logo"
            class="pointer-events-none absolute inset-0 z-[3]"
        >
          <a
              :key="activeSlide.id"
              :href="activeSlide.logo.href"
              :target="activeSlide.logo.newTab ? '_blank' : '_self'"
              :rel="
              activeSlide.logo.newTab
                ? 'noopener noreferrer'
                : undefined
            "
              :class="[
              'pointer-events-auto absolute -translate-x-1/2 -translate-y-1/2 transition-transform duration-300 ease-out',
              activeSlide.logo.linkClass,
            ]"
              :style="{
              width: activeSlide.logo.width,
              left: activeSlide.logo.positionX,
              top: activeSlide.logo.positionY,
              opacity: activeSlide.logo.opacity,
            }"
          >
            <img
                :src="activeSlide.logo.source"
                :alt="activeSlide.logo.alt"
                :class="[
                'h-auto w-full select-none object-contain',
                activeSlide.logo.imageClass,
              ]"
                draggable="false"
            />
          </a>
        </div>

        <div
            class="relative z-10 mx-auto flex h-full w-[calc(100%_-_2rem)] max-w-[1600px] flex-col justify-end pb-[40px] pt-[82px] sm:w-[calc(100%_-_3rem)] lg:w-[calc(100%_-_6rem)]"
        >
          <div
              class="flex w-full justify-center overflow-x-auto pb-1 [scrollbar-color:#7d693f_transparent]"
              @mouseenter="pauseCarousel('hover')"
              @mouseleave="resumeCarousel('hover')"
          >
            <div
                class="mx-auto grid w-full min-w-[1200px] max-w-[1450px] grid-cols-5 gap-4"
                role="tablist"
                aria-label="Select a creation"
            >
              <button
                  v-for="(slide, index) in slides"
                  :key="slide.id"
                  type="button"
                  role="tab"
                  :aria-selected="activeIndex === index"
                  :aria-label="`Show ${slide.title}, item ${index + 1} of ${slides.length}`"
                  class="relative grid h-[68px] min-w-0 grid-cols-[65px_minmax(0,1fr)] items-center gap-3 overflow-hidden rounded-md border-[1.5px] bg-transparent p-1.5 text-left transition-colors"
                  :class="
                  activeIndex === index
                    ? 'border-[#d9b86e]'
                    : 'border-white/30 hover:border-white/70'
                "
                  @click="selectSlide(index)"
              >
                <span
                    class="pointer-events-none absolute inset-0 z-0"
                    aria-hidden="true"
                >
                  <span
                      class="block h-full bg-[#c7a35a]/50 transition-[width] duration-75 ease-linear"
                      :style="{
                      width:
                        activeIndex === index
                          ? `${progress}%`
                          : '0%',
                    }"
                  ></span>
                </span>

                <span
                    class="relative z-10 block h-[54px] w-[65px] overflow-hidden rounded-lg"
                >
                  <img
                      v-if="slide.thumbnail"
                      :src="slide.thumbnail"
                      :alt="`${slide.title} preview`"
                      class="h-full w-full object-cover"
                      draggable="false"
                  />

                  <video
                      v-else
                      class="h-full w-full object-cover"
                      muted
                      playsinline
                      preload="metadata"
                      aria-hidden="true"
                  >
                    <source
                        :src="slide.video"
                        type="video/mp4"
                    />
                  </video>
                </span>

                <span class="relative z-10 min-w-0">
                  <strong
                      class="block truncate font-minecraft text-sm"
                  >
                    {{ slide.title }}
                  </strong>

                  <small
                      class="mt-1 block truncate text-[10px] font-bold uppercase tracking-[0.12em] text-[#d9b86e]"
                  >
                    {{ slide.subtitle }}
                  </small>
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>

      <a
          href="https://modrinth.com/server/brassworks-smp-official-server"
          target="_blank"
          rel="noopener noreferrer"
          class="see-more-button group absolute bottom-[5px] right-[5px] z-30 flex h-[55px] w-[233px] items-center justify-center px-8 text-base font-bold uppercase tracking-wide text-[#171614]"
      >
        <svg
            class="absolute inset-0 h-full w-full"
            viewBox="0 0 340 80"
            preserveAspectRatio="none"
            aria-hidden="true"
        >
          <defs>
            <clipPath id="see-more-shape">
              <path
                  d="
        M 25 0
        H 332
        Q 340 0 340 8
        V 44
        Q 340 49 336 53
        L 311 76
        Q 307 80 301 80
        H 8
        Q 0 80 0 72
        V 25
        Q 0 0 25 0
        Z
      "
              />
            </clipPath>
          </defs>

          <path
              fill="#c7a35a"
              d="
    M 25 0
    H 332
    Q 340 0 340 8
    V 44
    Q 340 49 336 53
    L 311 76
    Q 307 80 301 80
    H 8
    Q 0 80 0 72
    V 25
    Q 0 0 25 0
    Z
  "
          />

          <g clip-path="url(#see-more-shape)">
            <polygon
                class="see-more-wipe"
                points="-1200,-180 -160,-180 -420,160 -1200,160"
                fill="#dec17c"
            />
          </g>
        </svg>

        <span class="relative z-10">See more</span>
      </a>
    </div>
  </section>
</template>
